spring:
  application:
    name: eureka-client-feign-service
  profiles:
    active: @env@

server:
  port: 8763

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jm: DEBUG
