spring:
  application:
    name: eureka-client-greeting-service
  profiles:
    active: @env@

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jm: DEBUG
