spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: @env@
      discovery:
        enabled: true
        service-id: config-server
  profiles:
    active: @env@

server:
  port: 8766

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jm: DEBUG
