spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: @env@
      discovery:
        enabled: true
        service-id: config-server
  profiles:
    active: @env@

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
