spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: @env@
      discovery:
        enabled: true
        service-id: config-server
  profiles:
    active: @env@

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jm: DEBUG
