spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnnymillergh/spring-cloud-configuration
          search-paths: configuration
          username: puclic_repo_doesnt_need_username_and_password
          password: puclic_repo_doesnt_need_username_and_password
      label: master
  profiles:
    active: @env@

server:
  port: 8888

logging:
  config: classpath:configuration/logback/logback-@env@.xml
  # Configure logging level of project as DEBUG to enable SQL logging and other logging.
  level:
    com:
      jm: DEBUG
